---
abstract: 'extract PNG data from a Cairo::ImageSurface'
author:
  - 'Ben Bullock <bkb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::Depends: 0.2
  ExtUtils::MakeMaker: 0
  ExtUtils::PkgConfig: 1
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Image-PNG-Cairo
no_index:
  directory:
    - t
    - inc
requires:
  Cairo: 0
  Image::PNG::Libpng: 0.28
  perl: 5.008001
resources:
  bugtracker: https://github.com/benkasminbullock/image-png-cairo/issues
  repository: git://github.com/benkasminbullock/image-png-cairo.git
version: 0.05
